version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore: bump"
      prefix-development: "chore: bump"
      include: "scope"
    open-pull-requests-limit: 8
